version: "3.1"
services:
  web:
    build: ./web_service
    image: appsec4:latest
    ports:
      - "8080:5000"
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: "0.50"
          memory: 50M
        reservations:
          cpus: "0.25"
          memory: 20M
    environment:
      CSRF_KEY: /run/secrets/csrf_key
    secrets:
      - csrf_key
      - secretfile
  
secrets:
  csrf_key:
    external: true
  secretfile:
    file: secrets.yml
